### ISSUE TITLE
Windows Line Endings

### ISSUE THREAD

**Issue by DrLightsLab** [khwiri/cookiecutter-flask#1]
Windows line endings are causing the .nvmrc and .python-version files from being read during docker-compose up.  The RUN bash -c commands in the Dockerfiles under docker/-client and docker/-server directories include $(cat /filename/) which is failing due to the line endings.
```
Now using node v12.13.1 (npm v6.12.1)
Creating default alias: default -> 12.13.1 (-> v12.13.1 *)
' does not exist.n '12.13.1
 (-> N/A)> 12.13.1
N/A: version "default -> N/A" is not yet installed.

You need to run "nvm install default" to install it before using it.
ERROR: Service 'foo-client' failed to build: The command '/bin/sh -c bash -c "source /root/.bashrc &&     nvm install &&     nvm alias default $(cat .nvmrc) &&     nvm use default &&     npm install"' returned a non-zero code: 3
```

**Comment by khwiri** [comment]
Added proper eol handling with `.gitattributes` files. Also, added eol handling to `hooks/post_gen_project.py` script for initial rendering outside of git.
