### ISSUE TITLE
run.sh not found

### ISSUE THREAD

**Issue by DrLightsLab** [khwiri/cookiecutter-flask#2]
During docker-compose up, app-server_1 attempts to run run.sh under /root/ inside the docker container.  However, the file can't be found even though when everything is building, run.sh is shown under the /root/ directory if you print the contents of the directory.

```
Attaching to app-postgres_1, app-client_1, app-server_1
app-server_1    | /bin/sh: 1: ./docker/root/run.sh: not found
app-server_1 exited with code 127
```

**Comment by khwiri** [comment]
Added proper eol handling with `.gitattributes` files. Also, added eol handling to `hooks/post_gen_project.py` script for initial rendering outside of git.
